In [1]:
from pathlib import Path
import json
import pandas as pd
from tqdm import tqdm
import sys
sys.path.append("..")
from src.scene_pipeline import ScenePipeline
pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_rows", None)
pd.set_option("display.width", 2000)

In [2]:
DATA_DIR = Path("../data/diarized_samples")
json_paths = sorted(DATA_DIR.glob("videoplayback_20s_diarized_*.json"))
print(f"Найдено файлов: {len(json_paths)}")

Найдено файлов: 7

In [3]:
pipeline = ScenePipeline()

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Чтение json

In [4]:
results = {}
for path in tqdm(json_paths, desc="Обработка файлов"):
    with path.open("r", encoding="utf-8") as f:
        payload = json.load(f)
    result = pipeline.process(payload)
    results[path.name] = {
        "payload": payload,
        "result": result,
    }
print("Все файлы обработаны.")

Обработка файлов: 100%|███████████████████████████| 7/7 [05:45<00:00, 49.31s/it]

Все файлы обработаны.

Этап 1:

In [5]:
for name, data in results.items():
    print("\n" + "="*80)
    print(f"Исходные сегменты — {name}")
    print("="*80)
    payload = data["payload"]
    df = pd.DataFrame(payload["segments"])[["id", "start", "end", "speaker", "text"]]
    display(df)

================================================================================
Исходные сегменты — videoplayback_20s_diarized_0.json
================================================================================

         id  start    end speaker                                                           text
0  seg_0001   0.18   0.82      S0                                                        безумец
1  seg_0002   1.09   2.26      S0                                                   но вменяемый
2  seg_0003   2.56   8.01      S0  на прошлой неделе хотел бежать реанимировал скоро разве ах-ах
3  seg_0004   9.03  10.11      S1                                                 это мой парень
4  seg_0005  13.41  15.05      S1                                     четние испортили таторушка
5  seg_0006  15.34  16.57      S2                               человек-то видел мистера мердор?
6  seg_0007  16.57  18.44      S1                                       знак батальона рейнджера
7  seg_0008  18.68  19.81      S2                                                   миндор мертв

================================================================================
Исходные сегменты — videoplayback_20s_diarized_1.json
================================================================================

         id  start    end speaker                                                           text
0  seg_0001   1.03   2.04      S0                                                   места стоять
1  seg_0002   2.04   4.35      S1                         эндрю нет нет меня зовут элли виллберн
2  seg_0003   4.67   5.79      S1                                                 эдвард деннилс
3  seg_0004   6.12   8.08      S1                       здесь патроны есть я повесу чувствую ааа
4  seg_0005   8.25  10.88      S0                    ясно а это твои оружие маршал ты уверен там
5  seg_0006  10.71  14.02      S1          там слева мои инициалы она свалится рапина от пуля яс
6  seg_0007  14.21  16.67      S1                     и на этот раз вы мне может не вынете но ты
7  seg_0008  16.47  19.93      S2  ну так стреляй потому что лишь так ты сможешь удрать сострова

================================================================================
Исходные сегменты — videoplayback_20s_diarized_2.json
================================================================================

         id  start    end speaker                                                  text
0  seg_0001   0.74   3.41      S0      извините помогите мне у меня шина сэлдон и роман
1  seg_0002   3.42   5.94      S1  очень жаль но мне пора я могу опоздать что-то не так
2  seg_0003   5.94   8.43      S0                что лучше опоздать и умереть?аааа аааа
3  seg_0004   8.97   9.94      S1                                      не советую детка
4  seg_0005   9.94  10.93      S0                                       вы иди из тачки
5  seg_0006  12.84  13.41      S0                                                   ууу
6  seg_0007  13.77  15.07      S0                                        давайте ребята
7  seg_0008  15.08  16.15      S0                                            а ну пошли
8  seg_0009  16.38  18.21      S1                               аккуратнее совсем новое
9  seg_0010  18.51  19.98      S0                   нуль проблем стой иди влезай садись

================================================================================
Исходные сегменты — videoplayback_20s_diarized_3.json
================================================================================

          id  start    end speaker                                     text
0   seg_0001   0.23   1.60      S0       а друг мою все-таки заражено в шок
1   seg_0002   1.89   2.92      S1                   но раз бы уже не стало
2   seg_0003   3.17   4.32      S1                   нет никакого заражения
3   seg_0004   4.99   5.77      S1                  все это ложь идиота вон
4   seg_0005   8.16   8.62      S0                                       ээ
5   seg_0006   9.40   9.95      S1                                  не знаю
6   seg_0007  11.07  11.93      S2            да она живая не встала и на д
7   seg_0008  13.48  14.26      S0                        объясни нам матча
8   seg_0009  14.61  15.49      S0                     почему они нам врут?
9   seg_0010  15.76  17.28      S0  чтобы вы не узнали кто он на самом деле
10  seg_0011  17.61  18.49      S0                            на самом деле
11  seg_0012  18.63  19.47      S0                             и кто же мы?
12  seg_0013  19.50  19.98      S0                                но хорошо

================================================================================
Исходные сегменты — videoplayback_20s_diarized_4.json
================================================================================

          id  start    end speaker                                    text
0   seg_0001   0.13   1.03      S0                          прошу прощения
1   seg_0002   1.03   1.79      S1                              что такое?
2   seg_0003   1.89   3.25      S0             кде тут семнадцатый кабинет
3   seg_0004   3.64   4.60      S1                                   о это
4   seg_0005   4.96   7.49      S1                кродоешь энциклопедий не
5   seg_0006   7.49   9.78      S0   нет он выглядит как подменный учитель
6   seg_0007   9.78  10.26      S1                        минуты в ладонке
7   seg_0008  10.49  12.87      S0       саня меня зовут мистер эбби гнэлд
8   seg_0009  10.54  10.86      S1                                   а нет
9   seg_0010  13.67  14.34      S2                                 эбигнай
10  seg_0011  13.68  14.21      S0                     эбби герой сестра в
11  seg_0012  14.34  14.66      S0                             элли урагин
12  seg_0013  14.66  18.44      S2  не бегнули не бегнели мистер эбби гнев
13  seg_0014  18.48  18.96      S0       простите как вы делаете это не то
14  seg_0015  18.96  19.98      S2                    как вызову рэлли урб

================================================================================
Исходные сегменты — videoplayback_20s_diarized_5.json
================================================================================

         id  start    end speaker                                                                    text
0  seg_0001   0.12   0.99      S0                                                         и напиток ссссс
1  seg_0002   1.33   5.48      S1     давайте я заплачу за заказ следующего парня оформите как предоплату
2  seg_0003   5.55   6.98      S0                                         надо же какой вы щедрый ищите в
3  seg_0004   7.07   9.95      S1  а-то кто знает может следующий сделает так же что и не будет ни в коем
4  seg_0005   9.95  11.71      S0                                     готово хорошего вам дня си вярнется
5  seg_0006  15.96  19.98      S1      стойте нет не смейте пустите меня первым мне очень надо ваше время

================================================================================
Исходные сегменты — videoplayback_20s_diarized_6.json
================================================================================

          id  start    end speaker                                                             text
0   seg_0001   0.13   0.59      S0                                                         чаоаннлл
1   seg_0002   1.48   1.84      S1                                                             как?
2   seg_0003   2.61   5.06      S0                 какая разница перенесите нас отсюда скорее ааааа
3   seg_0004   5.55   6.17      S0                                                      мы не можем
4   seg_0005   9.43  11.39      S1  вони сказали мама можно и так далее все это было в течение года
5   seg_0006  11.71  12.65      S1                                                           сэмдин
6   seg_0007  13.01  13.72      S1                                                   рад вас видеть
7   seg_0008  14.46  15.05      S1                                                           бэлдор
8   seg_0009  15.71  16.37      S1                                             не надо это не нужно
9   seg_0010  16.86  18.32      S1                             думаешь вы хозяева планеты и рамкинг
10  seg_0011  19.00  19.98      S1                                               кто дает вам право

Этап 2:

In [6]:
for name, data in results.items():
    print("\n" + "="*80)
    print(f"После нормализации текста — {name}")
    print("="*80)
    result = data["result"]
    segs = result["segments"]
    df = pd.DataFrame(segs)[
        ["id", "start", "end", "speaker", "text", "normalized_text"]
    ]
    display(df)

================================================================================
После нормализации текста — videoplayback_20s_diarized_0.json
================================================================================

         id  start    end speaker                                                           text                                                    normalized_text
0  seg_0001   0.18   0.82      S0                                                        безумец                                                           безумец.
1  seg_0002   1.09   2.26      S0                                                   но вменяемый                                                          Вменяемый
2  seg_0003   2.56   8.01      S0  на прошлой неделе хотел бежать реанимировал скоро разве ах-ах  На прошлой неделе хотел бежать, реанимировал, скоро, разве ах-ах.
3  seg_0004   9.03  10.11      S1                                                 это мой парень                                                    Это мой парень.
4  seg_0005  13.41  15.05      S1                                     четние испортили таторушка                                         Чтение испортила таторушка
5  seg_0006  15.34  16.57      S2                               человек-то видел мистера мердор?                                   Человек-то видел Мистера Мердor?
6  seg_0007  16.57  18.44      S1                                       знак батальона рейнджера                                           Знак батальона Рейнджера
7  seg_0008  18.68  19.81      S2                                                   миндор мертв                                                      Миндор мертв.

================================================================================
После нормализации текста — videoplayback_20s_diarized_1.json
================================================================================

         id  start    end speaker                                                           text                                                    normalized_text
0  seg_0001   1.03   2.04      S0                                                   места стоять                                                      Места стоять.
1  seg_0002   2.04   4.35      S1                         эндрю нет нет меня зовут элли виллберн                              Эндрю, нет, меня зовут Элли Виллберн.
2  seg_0003   4.67   5.79      S1                                                 эдвард деннилс                                                     Эдвард Деннилс
3  seg_0004   6.12   8.08      S1                       здесь патроны есть я повесу чувствую ааа                        Здесь патроны есть, я повеслю, чувствую ааа
4  seg_0005   8.25  10.88      S0                    ясно а это твои оружие маршал ты уверен там                   Ясно, а это твоё оружие, маршал? Ты уверен, там?
5  seg_0006  10.71  14.02      S1          там слева мои инициалы она свалится рапина от пуля яс  Там слева мои инициалы. Она сгнулась, рука повисла, от пули ясно.
6  seg_0007  14.21  16.67      S1                     и на этот раз вы мне может не вынете но ты                              и на этот раз вы мне не вынете, но ты
7  seg_0008  16.47  19.93      S2  ну так стреляй потому что лишь так ты сможешь удрать сострова   Ну так стреляй, потому что лишь так ты сможешь удрать с трупами.

================================================================================
После нормализации текста — videoplayback_20s_diarized_2.json
================================================================================

         id  start    end speaker                                                  text                                           normalized_text
0  seg_0001   0.74   3.41      S0      извините помогите мне у меня шина сэлдон и роман       Извините, помогите мне. У меня шина Селдон и роман.
1  seg_0002   3.42   5.94      S1  очень жаль но мне пора я могу опоздать что-то не так  Очень жаль, но мне пора. Я могу опоздать. Что-то не так?
2  seg_0003   5.94   8.43      S0                что лучше опоздать и умереть?аааа аааа                      Что лучше: опоздать и умереть? Ааааа
3  seg_0004   8.97   9.94      S1                                      не советую детка                                        Не советую, детка.
4  seg_0005   9.94  10.93      S0                                       вы иди из тачки                                          Вы иди из тачки.
5  seg_0006  12.84  13.41      S0                                                   ууу                                                       uuu
6  seg_0007  13.77  15.07      S0                                        давайте ребята                                           давайте, ребята
7  seg_0008  15.08  16.15      S0                                            а ну пошли                                              А ну, пошли.
8  seg_0009  16.38  18.21      S1                               аккуратнее совсем новое                                 Аккуратнее, совсем новое.
9  seg_0010  18.51  19.98      S0                   нуль проблем стой иди влезай садись                      Ну ладно, стой, иди, влезай, садись.

================================================================================
После нормализации текста — videoplayback_20s_diarized_3.json
================================================================================

          id  start    end speaker                                     text                                  normalized_text
0   seg_0001   0.23   1.60      S0       а друг мою все-таки заражено в шок              А друг мой все-таки заражено в шок.
1   seg_0002   1.89   2.92      S1                   но раз бы уже не стало                              но раз уже не стало
2   seg_0003   3.17   4.32      S1                   нет никакого заражения                          нет никакого заражения.
3   seg_0004   4.99   5.77      S1                  все это ложь идиота вон                             Все это ложь, идиот!
4   seg_0005   8.16   8.62      S0                                       ээ                                               Ээ
5   seg_0006   9.40   9.95      S1                                  не знаю                                         Не знаю.
6   seg_0007  11.07  11.93      S2            да она живая не встала и на д  Да она живая, не встала и на дыбы не поднялась.
7   seg_0008  13.48  14.26      S0                        объясни нам матча                                Объясни нам матч.
8   seg_0009  14.61  15.49      S0                     почему они нам врут?                             Почему они нам врут?
9   seg_0010  15.76  17.28      S0  чтобы вы не узнали кто он на самом деле        Чтобы вы не узнали, кто он на самом деле.
10  seg_0011  17.61  18.49      S0                            на самом деле                                   На самом деле.
11  seg_0012  18.63  19.47      S0                             и кто же мы?                                     и кто же мы?
12  seg_0013  19.50  19.98      S0                                но хорошо                                       но хорошо.

================================================================================
После нормализации текста — videoplayback_20s_diarized_4.json
================================================================================

          id  start    end speaker                                    text                            normalized_text
0   seg_0001   0.13   1.03      S0                          прошу прощения                            Прошу прощения.
1   seg_0002   1.03   1.79      S1                              что такое?                                 Что такое?
2   seg_0003   1.89   3.25      S0             кде тут семнадцатый кабинет            Куда здесь семнадцатый кабинет?
3   seg_0004   3.64   4.60      S1                                   о это                                        Это
4   seg_0005   4.96   7.49      S1                кродоешь энциклопедий не                   Крёдоешь энциклопедий не
5   seg_0006   7.49   9.78      S0   нет он выглядит как подменный учитель    нет, он выглядит как подменный учитель.
6   seg_0007   9.78  10.26      S1                        минуты в ладонке                          Минуты в ладонке.
7   seg_0008  10.49  12.87      S0       саня меня зовут мистер эбби гнэлд        Саня, меня зовут Мистер Эбби Гнэлд.
8   seg_0009  10.54  10.86      S1                                   а нет                                     А нет.
9   seg_0010  13.67  14.34      S2                                 эбигнай                                    Эбигней
10  seg_0011  13.68  14.21      S0                     эбби герой сестра в                        Эбби героя сестра в
11  seg_0012  14.34  14.66      S0                             элли урагин                                Элли Урагин
12  seg_0013  14.66  18.44      S2  не бегнули не бегнели мистер эбби гнев  Не бегнули, не бегнели, мистер Эбби гнев.
13  seg_0014  18.48  18.96      S0       простите как вы делаете это не то       Прости, как ты это делаешь - не так.
14  seg_0015  18.96  19.98      S2                    как вызову рэлли урб                     Как вызвать релий urb?

================================================================================
После нормализации текста — videoplayback_20s_diarized_5.json
================================================================================

         id  start    end speaker                                                                    text                                                                    normalized_text
0  seg_0001   0.12   0.99      S0                                                         и напиток ссссс                                                                   Инспиток с ССССС
1  seg_0002   1.33   5.48      S1     давайте я заплачу за заказ следующего парня оформите как предоплату            Давайте, я заплачу за заказ, следующего парня. Оформите как предоплату.
2  seg_0003   5.55   6.98      S0                                         надо же какой вы щедрый ищите в                                                  Надо же, такой вы щедрый! Ищете в
3  seg_0004   7.07   9.95      S1  а-то кто знает может следующий сделает так же что и не будет ни в коем  а-то, кто знает, может, следующий сделает так же, чтобы не было ни в коем случае.
4  seg_0005   9.95  11.71      S0                                     готово хорошего вам дня си вярнется                                     Готово, хорошего вам дня! Всегда возвращается.
5  seg_0006  15.96  19.98      S1      стойте нет не смейте пустите меня первым мне очень надо ваше время           Стойте! Нет, не смейте! Пустите меня первым! Мне очень нужно ваше время!

================================================================================
После нормализации текста — videoplayback_20s_diarized_6.json
================================================================================

          id  start    end speaker                                                             text                                                         normalized_text
0   seg_0001   0.13   0.59      S0                                                         чаоаннлл                                                                     Чао
1   seg_0002   1.48   1.84      S1                                                             как?                                                                    Как?
2   seg_0003   2.61   5.06      S0                 какая разница перенесите нас отсюда скорее ааааа                            Какая разница, перенесите нас отсюда скорее!
3   seg_0004   5.55   6.17      S0                                                      мы не можем                                                            мы не можем.
4   seg_0005   9.43  11.39      S1  вони сказали мама можно и так далее все это было в течение года  Вони сказали: "Мама, можно", и так далее. Все это было в течение года.
5   seg_0006  11.71  12.65      S1                                                           сэмдин                                                                  Сэмдин
6   seg_0007  13.01  13.72      S1                                                   рад вас видеть                                                         Рад вас видеть.
7   seg_0008  14.46  15.05      S1                                                           бэлдор                                                                  Белдор
8   seg_0009  15.71  16.37      S1                                             не надо это не нужно                                                  Не надо, это не нужно.
9   seg_0010  16.86  18.32      S1                             думаешь вы хозяева планеты и рамкинг                                     думаешь ты хозяин планеты, Рамкинг?
10  seg_0011  19.00  19.98      S1                                               кто дает вам право                                                      Кто дает вам право

Этап 3:

In [7]:
for name, data in results.items():
    print("\n" + "="*80)
    print(f"Сцены по спикерам — {name}")
    print("="*80)

    speakers = data["result"]["speakers"]

    rows = []
    for sp in speakers:
        sc = sp.get("scene", {}) or {}
        details = sc.get("details") or []
        details = ", ".join(details) if isinstance(details, list) else str(details)

        rows.append({
            "speaker": sp.get("speaker"),
            "full_text": sp.get("text"),
            "scene": sc.get("scene", ""),
            "style": sc.get("style", ""),
            "details": details,
            "visual_prompt": sp.get("visual_prompt")
        })

    df = pd.DataFrame(rows)
    display(df)

================================================================================
Сцены по спикерам — videoplayback_20s_diarized_0.json
================================================================================

  speaker                                                                             full_text                                                                                                                     scene        style                                                                                                                                details                                                              visual_prompt
0      S0  безумец. Вменяемый На прошлой неделе хотел бежать, реанимировал, скоро, разве ах-ах.  Улица с забором и домами по обе стороны, человек в штатском одет, держит руку на животе, лицо мрачное, глаза испуганные.      усталый                                                  человек в штатском, забор по бокам, дома по обе стороны, рука на животе, мрачное лицо  Street with fence, man in shabby clothes holding stomach, frightened eyes
1      S1                   Это мой парень. Чтение испортила таторушка Знак батальона Рейнджера                                         парень с читаемым телефоном на коленях, фоном городской улицы под вечерним светом  современный  парень в джинсах и свитере, читает смартфон, лицо сосредоточенное, фоном является городская улица, свет от телефона освещает его лицо   a boy in jeans and a sweater reading a smartphone on his knees on a city
2      S2                                        Человек-то видел Мистера Мердor? Миндор мертв.                                                   Улица с домами из кирпича, один из которых разрушен, люди проходят мимо   устаревший                                                     разрушенный дом, проходящие люди, утоптанная земля, старая лампа, стены из кирпича    Street with brick houses, one destroyed, people pass by. Outdated style

================================================================================
Сцены по спикерам — videoplayback_20s_diarized_1.json
================================================================================

  speaker                                                                                                                                                                                                 full_text                                                                                                                                          scene            style                                                                                                                  details                                                               visual_prompt
0      S0                                                                                                                                            Места стоять. Ясно, а это твоё оружие, маршал? Ты уверен, там?                                                                         Маршал стоит перед массивным столом с картами, на котором лежит копье.       формальный                    массивный деревянный стол, карты на столе, копье на столе, маршал в офицерской форме, воздух напряжен   Marshal in an officer's uniform stands before a massive wooden table with
1      S1  Эндрю, нет, меня зовут Элли Виллберн. Эдвард Деннилс Здесь патроны есть, я повеслю, чувствую ааа Там слева мои инициалы. Она сгнулась, рука повисла, от пули ясно. и на этот раз вы мне не вынете, но ты                                                               Улица ночью, на ней лежит труп с повешенным телом, рядом пистолет и надпись И.В.  темное, мрачное                                       темная улица, повешенный труп, пистолет, письменный блок с инициалами, ночное небо  Street at night, corpse hung, pistol nearby, dark scene with initials on a
2      S2                                                                                                                                          Ну так стреляй, потому что лишь так ты сможешь удрать с трупами.  Узкая улица с вывеской магазина на стене справа, два трупа лежат на асфальте слева, один человек стоит спиной к зрителю, держа оружие в руке.          усталый  вывеска магазина на стене, два трупа на асфальте, человек держит оружие, лицо человека не видно, лицо человека не видно      Narrow street with a hanging store sign, two bodies on the pavement, a

================================================================================
Сцены по спикерам — videoplayback_20s_diarized_2.json
================================================================================

  speaker                                                                                                                                                                        full_text                                                                                        scene                 style                                                                                                                                                                                     details                                                                visual_prompt
0      S0  Извините, помогите мне. У меня шина Селдон и роман. Что лучше: опоздать и умереть? Ааааа Вы иди из тачки. uuu давайте, ребята А ну, пошли. Ну ладно, стой, иди, влезай, садись.  Мужчина в джинсах и куртке стоит у тротуара, рядом с его машиной, которая стоит на обочине.  усталый, решительный  мужчина в черных джинсах и сером пиджаке, машина с признаками ремонта на обочине, лицо мужчины выглядит усталым и обеспокоенным, мужчина смотрит на дорогу, мужчина смотрит на собеседника    A man in jeans and a jacket stands on the sidewalk next to his car, tired
1      S1                                                                            Очень жаль, но мне пора. Я могу опоздать. Что-то не так? Не советую, детка. Аккуратнее, совсем новое.                               Улица с вывеской "Детский магазин" и старым фонариком на углу.  устаревшая, скромная                                                                                                     старый фонарик, вывеска магазина, старая лавка, дверь магазина, старые деревянные полки  Street with sign 'Children's Store' and old lantern at the corner. Outdated

================================================================================
Сцены по спикерам — videoplayback_20s_diarized_3.json
================================================================================

  speaker                                                                                                                                                       full_text                                                                                          scene                style                                                                                                     details                                                              visual_prompt
0      S0  А друг мой все-таки заражено в шок. Ээ Объясни нам матч. Почему они нам врут? Чтобы вы не узнали, кто он на самом деле. На самом деле. и кто же мы? но хорошо.  Мужчина в черной футболке сидит на скамейке под звездным небом, его лицо напряженно вытянуто.          напряженный                        мужчина в черной футболке, скамейка, звездное небо, лицо мужчины напряженно вытянуто       Man in a black shirt sits on a bench under a starry sky, tense face.
1      S1                                                                                       но раз уже не стало нет никакого заражения. Все это ложь, идиот! Не знаю.          Улица безлюдная, освещенная тусклым светом фонарей, на фоне небольшой зеленой рощицы.  холодный, спокойный                          пустая улица, тусклые фонари, зеленая роща, небольшая поляна, пустые домашние окна         Street deserted, dim streetlights, small green grove, calm, empty.
2      S2                                                                                                                 Да она живая, не встала и на дыбы не поднялась.                                                               женщина лежит на кровати без сна       непринужденная  постельное белье, кровать, лицо женщины покрыто тонкой пленкой пота, руки сложены на груди, лицо спокойное  woman lies on the bed without sleeping, relaxed, bedding, hands folded on

================================================================================
Сцены по спикерам — videoplayback_20s_diarized_4.json
================================================================================

  speaker                                                                                                                                                                                         full_text                                                                   scene                   style                                                                                                              details                                                                visual_prompt
0      S0  Прошу прощения. Куда здесь семнадцатый кабинет? нет, он выглядит как подменный учитель. Саня, меня зовут Мистер Эбби Гнэлд. Эбби героя сестра в Элли Урагин Прости, как ты это делаешь - не так.  Учительский зал с пустыми партами и столами, освещенный дневным светом  холодный и официальный                                                         пустые парты, столы, дверь, свет от окна, тусклый свет лампы    Teacher's hall with empty desks and tables, illuminated by daylight. Cold
1      S1                                                                                                                                  Что такое? Это Крёдоешь энциклопедий не Минуты в ладонке. А нет.  Старый человек сидит на скамейке у тротуара под ярким солнечным светом                 усталый  старик в сером пальто, скамейка из твердой древесины, солнце светит прямо в лицо, тротуар с разметкой, вокруг пусто  Old man in gray coat sits on wooden bench under sidewalk markings in bright
2      S2                                                                                                                          Эбигней Не бегнули, не бегнели, мистер Эбби гнев. Как вызвать релий urb?  Улица ночью, пара прохожих, один человек стоит на тротуаре, озирается.        темное, холодное          один человек в темной одежде, лицо человека смотрит в сторону, тротуар с лампочками, фон - городские здания    Street at night, pedestrians, one person stands on sidewalk, looks around

================================================================================
Сцены по спикерам — videoplayback_20s_diarized_5.json
================================================================================

  speaker                                                                                                                                                                                                                           full_text                                                                        scene       style                                                                                                  details                                                                visual_prompt
0      S0                                                                                                                                   Инспиток с ССССС Надо же, такой вы щедрый! Ищете в Готово, хорошего вам дня! Всегда возвращается.  Щедрая инспекторша с надписью ССССС на белом фоне, улыбается и машет рукой.  формальная  инспекторша в форме школы, надпись ССССС на белом фоне, улыбающаяся инспекторша, машет рукой, белый фон   Generous inspector with inscription CCCSS on white background, smiling and
1      S1  Давайте, я заплачу за заказ, следующего парня. Оформите как предоплату. а-то, кто знает, может, следующий сделает так же, чтобы не было ни в коем случае. Стойте! Нет, не смейте! Пустите меня первым! Мне очень нужно ваше время!                  парень суетится возле кассы с багажом, ожидая своей очереди   нервозный     парень в черной футболке и джинсах, заполненная касса, багаж на руках, люди в толпе, вокруг светофор  A boy rushes with luggage near a filled cash register, waiting nervously in

================================================================================
Сцены по спикерам — videoplayback_20s_diarized_6.json
================================================================================

  speaker                                                                                                                                                                                full_text                                                                   scene                  style                                                                                                                                 details                                                             visual_prompt
0      S0                                                                                                                            Чао Какая разница, перенесите нас отсюда скорее! мы не можем.                    двое мужчин стоят на платформе перед закрытой дверью  усталый и напряженный       мужчины в черных костюмах, дверь с надписью 'Закрыто', платформа с металлическими бордюрами, мужчины ссутулены, фон - серые стены  two men in black suits stand on metal railings in front of a closed door
1      S1  Как? Вони сказали: "Мама, можно", и так далее. Все это было в течение года. Сэмдин Рад вас видеть. Белдор Не надо, это не нужно. думаешь ты хозяин планеты, Рамкинг? Кто дает вам право  Старый дом с выцветшей краской на стене и старыми деревянными дверьми.   устаревший, скромный  старая деревянная дверь, выцветшая краска на стене, старые телевизоры, стул с выгоревшей обивкой, старый стол с разбросанными бумагами    Old house with faded paint on the walls and old wooden doors, outdated